### ISSUE TITLE
Can't get it working..

### ISSUE THREAD

**Issue by LudvigAstrom** [bengtner/batterycontrol#2]
Trying to run the script but I'm stuck.

I keep getting this:

File "./battery.py", line 581
    while True:
        ^
IndentationError: expected an indented block

**Comment by bengtner** [comment]
Oops, I have merged a pull request and it seems lite this caused a problem. There are two lines "while True" Remove one of the , e.g  #579, and this problem should go away.

**Comment by LudvigAstrom** [comment]
Thanks, seemed to solve that problem, but now I'm getting this instead:


Segment start hour: 0
Traceback (most recent call last):
  File "/home/pi/battery.py", line 619, in <module>
    main()
  File "/home/pi/battery.py", line 517, in main
    vector = buildOptimizedChargeCntrlVector(pdata['data']['viewer']['homes'][0]['currentSubscription']['priceInfo']['today'], bLogger)
  File "/home/pi/battery.py", line 202, in buildOptimizedChargeCntrlVector
    segments = priceSegments(data, logger)
  File "/home/pi/battery.py", line 358, in priceSegments
    peaks, _ = find_peaks(prices)
NameError: name 'find_peaks' is not defined

**Comment by bengtner** [comment]
find_peaks is defined in a python package imported in the beginning of the file:

from scipy.signal import find_peaks

It looks like you miss this module scipy.signal on your system. You need to install this.  You can find  out how by googling....

**Comment by LudvigAstrom** [comment]
I think i got it running now.
Apparently i somehow managed to delete 

"from scipy.signal import find_peaks"

Added it again and now it seems to run properly. Thanks!

**Comment by bengtner** [comment]
I have made quite a few updates beside your pull request. Unfortunately, I was lost in in git and realized I have made a all changes in a detached state. So now I created a new branch, nextstep, wich includes all my additions beside your pull request. This branch is called "nextstep". So please use this instead of "mailn". I don't know if have have pulled the whole repo, so I don't want to mess up things by renaming the branch. Just forget main to put it simple.....

**Comment by LudvigAstrom** [comment]
Thanks, what’s the update, anything major?

Unfortunately I'm pretty useless at programming / python but I'm trying to learn.

However, I have an idea for an extension that I thought I would share with you. However, don't know how complicated it is to implement, so do what you want with the idea.

I have seen that there will be some days when it is not worth charging and selling and when the script says "Idle" all day. On such days, you could have put a full charge on "Low" and then use it for self-consumption during the day, i.e. switch to maximizing self-consumption but skip 0 as maximum input/output.

I'm thinking of another position on the helper which is called self-consumption.

Then there are days where it is cheaper to charge in the evening (like 22-00) than on the following night, it would have been nice if you could intercept it in some way to optimize. :)

Best regards

**Comment by bengtner** [comment]
I have just pushed an updated version. The one you looked  at is a non working version due to I screwed up my git repo....
This version includes some  of the improvements you propose. For instance, it will set battery mode to "maximize selfconsumtion" if the price curve is to flat. 

But the biggest improvement is related to the prize curve analysis. It now makes a single segment analysis of the full day and also makes a multisegment analysis where individual peaks are identfied. Single segment is compared with the outcome of a multi segment approach before the final charging vector is defined.

Another improvement comes from @MichaelPihlblad. This adds two attributes to the entity input_select.battery_mode. Those attributes will contain today's and tomorrow's charging vector. By this those can be displayed in HA on a MD card. Just add a MD card and include the following templates:

{{state_attr("input_select.battery_mode","Today") }}
{{state_attr("input_select.battery_mode","Tomorrow")}}

If there is no vector (like it is today), "None" will be displayed.

I have also though about implementing a sliding window, so the analysis can span over midnight, Howver, I have not done anything on this so far. It makes things more complex and the gain is quite limited.
